# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"
  # variables:
  #   npm_config_cache: $(Pipeline.Workspace)/.npm

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  # - task: CacheBeta@0
  #   inputs:
  #     key: npm | $(Agent.OS) | package-lock.json
  #     path: $(npm_config_cache)
  #   displayName: Cache npm

  - script: |
      npm install
      npm run build
    displayName: "npm install and build"

  - script: |
      npm test
    displayName: "npm test"

  - script: |
      cd e2e-tests
      npm install
      ulimit -c unlimited
      npm run test
      # Exit if the npm run test was not a success
      if [ $? -ne 0 ] ; then exit 1 ; fi
      cd ..
    displayName: "End to End (E2E) Tests"
